export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_BY_CATEGORY = 'GET_PRODUCTS_BY_CATEGORY';
export const GET_PRODUCTS_BY_ID = 'GET_PRODUCTS_BY_ID';
export const GET_PRODUCTS_BY_CATEGORY_SLIDE1 = 'GET_PRODUCTS_BY_CATEGORY_SLIDE1';
export const GET_PRODUCTS_BY_CATEGORY_SLIDE2 = 'GET_PRODUCTS_BY_CATEGORY_SLIDE2';
export const GET_PRODUCTS_BY_CATEGORY_SLIDE3 = 'GET_PRODUCTS_BY_CATEGORY_SLIDE3';


export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_CATEGORY_ROOT = 'GET_CATEGORY_ROOT';

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const DELETE_PRODUCT_FROM_CART = 'DELETE_PRODUCT_FROM_CART';
export const SUBMIT_CART = 'SUBMIT_CART';
export const GET_CART = 'GET_CART';
export const UPDATE_PRODUCT_FROM_CART = 'UPDATE_PRODUCT_FROM_CART';

